### ISSUE TITLE
how to use it

### ISSUE THREAD

**Issue by flakka2022** [nimaltd/RemoteDecoder#10]
hello , thanks for your great repository . i have a question which is how i can use this to transmit via [FSK-4A PT2262](https://www.jahankitshop.com/market/d/6630) ? example code works ? how to wire up this to esp32 ?

**Comment by nimaltd** [comment]
Hello. your welcome. esp32 has been ported. you can find it on port folder. add it to your project. i did test ev1527 and pt2262.

**Comment by flakka2022** [comment]
the fsk-4 that i have uses pt2262 and it is prebuilt module .  still it is possible to use your code ? or mine had pre set of codes and cannot be use with anyother microcontroller ? sorry for poor english . where can we talk farsi inja ya onja 😁 taze fahmidam author iranie .

**Comment by nimaltd** [comment]
اره فارسی بگو. من از ریموت اماده استفاده کردم و جواب داد. مشکلی نداشت

**Comment by flakka2022** [comment]
تشکر . ماژولی که دارم [این هست](https://m.de.aliexpress.com/item/1005003066064158.html?gps-id=platformRecommendH5&scm=1007.18499.332340.0&scm_id=1007.18499.332340.0&scm-url=1007.18499.332340.0&pvid=86ad65c1-da6a-4244-9437-b18073989d9b&_t=gps-id:platformRecommendH5,scm-url:1007.18499.332340.0,pvid:86ad65c1-da6a-4244-9437-b18073989d9b,tpp_buckets:668%232846%238107%231934&pdp_npi=3%40dis%21EUR%2115.57%2115.57%21%21%21%21%21%40211b443e16903946743278404e173b%2112000023738356912%21rec%21DE%21) و خودش از قبل یه pt2262 داشته . آیا باز هم امکان استفاده از کد جنابعالی و استفاده از میکروکنترلر برای ماژول هست ؟ چون خود ماژول قدرت مناسبی داره و به تنهایی از pt2262 نمیشه همچین قدرتی گرفت .

**Comment by nimaltd** [comment]
بله. مشکلی نداره
