### ISSUE TITLE
Algorithm to decode EV1527 and PT2262

### ISSUE THREAD

**Issue by jxltom** [nimaltd/RemoteDecoder#7]
I think the encode method for EV1527 and PT2262 are different?

How to decode them in the same way. In your code, I didn't find any differences. Thanks!

**Comment by nimaltd** [comment]
hello. they are the same in output wave.  every pt2262 bits (0-1-T) the same as 2  of ev1527 bits

**Comment by jxltom** [comment]
Thanks for the info!
